version: '3.8'

services:
  # ----------- db ----------- #
  postgres:
    image: postgres:16.1
    container_name: postgres
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRESQL_USER=${POSTGRES_USER}s
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - ALLOW_EMPTY_PASSWORD=${HIDE_EMPTY_PASSWORD}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}

  # ----------- bus ----------- #
  bus:
    image: jrgiadach/soabus:v1
    container_name: soabus
    restart: always
    ports:
      - "5000:5000"

  # ----------- servicios ----------- #
  serv-dbcon:
    build: ./servicios
    container_name: serv-dbcon
    command: sh -c "sleep 6 && python db_connect.py"
    depends_on:
      - postgres
      - bus
    volumes:
      - ./servicios:/usr/src/app